version: '3.8'

services:
  app:
    build: .
    container_name: emareflow
    ports:
      - "8800:8800"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
